Multiple optimization and fixes
ioBroker/ioBroker.javascript pull request #964
Opened 2022-02-23 20:15 UTC by Apollon77

2022-02-23 23:00 UTC, AlCalzone requested changes
To be honest, this is hard to digest on Github. Didn't see anything stand out at a first glance though, except some unreadable lines :)

2022-02-24 12:27 UTC, Apollon77 commented on lib/sandbox.js
> +                    return this[0] ? context.convertBackStringifiedValues(this[0], context.interimStateValues[this[0]] !== undefined ? context.interimStateValues[this[0]] : states[this[0]]) : null;
done, incl other places

2022-02-24 14:38 UTC, AlCalzone requested changes

2022-02-24 14:38 UTC, AlCalzone commented on lib/sandbox.js
> +                const foreignMethod = typeof adapter.setForeignBinaryStateAsync === 'function;'
```suggestion
                const foreignMethod = typeof adapter.setForeignBinaryStateAsync === 'function'
```

2022-02-24 15:56 UTC, Apollon77 commented on lib/sandbox.js
> +                const foreignMethod = typeof adapter.setForeignBinaryStateAsync === 'function;'
uuuuups ;-) thx

2022-03-01 07:46 UTC, merged